### ISSUE TITLE
Android 11 Startup loop. Not working in upstream as well.

### ISSUE THREAD

**Issue by kubo6472** [XiangRongLin/NewPipe-preuinified#3]
Screen recording the bug caused this issue to reset.
I tested the original app. Still the same thing.

https://user-images.githubusercontent.com/26146502/115139444-37ce2d80-a032-11eb-8b59-546ece2ed422.mp4

here's what happens when I click on any YouTube link in other apps and newpipe preunified is the default app to open. As per beginning this must be device specific.
I use only preunified, so I'd love if the fix I'm about to propose to upstream will be backported. I'll try my best testing and making some PR from the code.

**Comment by SpazMahTazz** [comment]
I get this issue in v0.21.2 running android 8.1

**Comment by kubo6472** [comment]
> I get this issue in v0.21.2 running android 8.1

What is your phone by any chance?

**Comment by SpazMahTazz** [comment]
> > I get this issue in v0.21.2 running android 8.1
> 
> What is your phone by any chance?

Blackberry keyone, my samsung galaxy tab a 10.5 on android 11 does it too. 0.21.0 works fine on both.

**Comment by kubo6472** [comment]
> > > I get this issue in v0.21.2 running android 8.1
> > 
> > 
> > What is your phone by any chance?
> 
> Blackberry keyone, my samsung galaxy tab a 10.5 on android 11 does it too. 0.21.0 works fine on both.

Really? Curious. Wait. I gotta try downgrading then.

**Comment by kubo6472** [comment]
Confirmed working. Thanks. Blaming 100% on the extractor then.

**Comment by kubo6472** [comment]
Tested, that it happened between the 0.21.0 and .1 and contrary to the main app, the newest extractor doesn't fix the issue. For now I'm sticking to using the old extractor.

**Comment by XiangRongLin** [comment]
@kubo6472 Do you know by chance which of the commits in #6053 fixed this? Then i can try to cherry pick it here

**Comment by kubo6472** [comment]
> 
> 
> @kubo6472 Do you know by chance which of the commits in #6053 fixed this? Then i can try to cherry pick it here

Nope, since I don't really understand it. But these three got my attention:
https://github.com/TeamNewPipe/NewPipe/pull/5999
https://github.com/TeamNewPipe/NewPipe/pull/5944
https://github.com/TeamNewPipe/NewPipeExtractor/pull/597

**Comment by XiangRongLin** [comment]
@kubo6472 Can you test this?

[app-release.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6440022/app-release.zip)

**Comment by SpazMahTazz** [comment]
> @kubo6472 Can you test this?
> 
> [app-release.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6440022/app-release.zip)

Just gave it a whirl on the keyone and it still spazzes out like OP's vid when clicking on a yt link.

**Comment by kubo6472** [comment]
> @kubo6472 Can you test this?
> 
> [app-release.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6440022/app-release.zip)

Tested, still loops.

**Comment by XiangRongLin** [comment]
[app-debug.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6440660/app-debug.zip)
Welp, it would have made sense to actually look at the logs and go from there, since i have android 11 too...

**Comment by XiangRongLin** [comment]
Fixed with 526bd59b3f1ffe7d4b54c231206bba0f31484003 and caaceb979459ad49ead9cbdf1b3ca7100d2feed5

**Comment by SpazMahTazz** [comment]
Hate to be a downer, but I still get this issue on v0.21.2.1 with the keyone.

**Comment by XiangRongLin** [comment]
Hmm...

Im pretty sure it's occuring because of the the ErrorInfo change to use the Parcelize annotation. While displaying the error screen, it throws a new one, which causes the loop.
I pretty sure it's this because there was the same issue in the main repo, which i thought was was solved by the commit i cherry picked.

**Comment by SpazMahTazz** [comment]
Well if you need me to do any testing just let me know. That's about all I can do.

**Comment by XiangRongLin** [comment]
[app-release.zip](https://github.com/XiangRongLin/NewPipe-preuinified/files/6525999/app-release.zip)
I feel like i either uploaded the wrong app or generated it from old sources.

**Comment by SpazMahTazz** [comment]
I can open YouTube links with that apk, thanks!

**Comment by kubo6472** [comment]
Yep this works. Sorry I didn't let you know sooner that the previous fix didn't work.
